version: '3'
services:

  django:
    build: ./django
    image: django
    volumes:
      - gateway:/usr/src/app
    container_name: django
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db

  user_api:
    build: ./user_api
    image: user_api
    volumes:
      - vol_user_api:/usr/src/app
    container_name: user_api
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - db


  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - vol_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user 
      POSTGRES_DB: db_name


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8008:8080

volumes:
  gateway:
    driver: local
    driver_opts:
      type: none
      device: /Users/eboulhou/Desktop/docker_trans/volumes/gateway
      o: bind

  vol_user_api:
    driver: local
    driver_opts:
      type: none
      device: /Users/eboulhou/Desktop/docker_trans/volumes/user_api
      o: bind
  vol_db:
    driver: local
    driver_opts:
      type: none
      device: /Users/eboulhou/Desktop/docker_trans/volumes/db
      o: bind
  




